exp_name: AE_mnist_shifted
data:
  training:
    dataset: mnist
    root: './dataset'
    type: shift
    shift_range: 10
    digit: 3
    batch_size: 10
model:
  arch: ae
  encoder:
      arch: fc_image
      l_hidden: [512, 512, 512, ]
      activation: ['relu', 'relu', 'relu', ]
      out_activation: 'linear'
  decoder:
      arch: fc_image
      l_hidden: [512, 512, 512, ]
      activation: ['relu', 'relu', 'relu', ]
      out_activation: 'sigmoid'
  x_dim: 784
  z_dim: 1
optimizer:
  lr: 0.001
training:
  num_epochs: 1001
