exp_name: AE_mnist_rotated
data:
  training:
    dataset: mnist
    root: './dataset'
    type: rotate
    digit: 7
    batch_size: 50
model:
  arch: ae
  encoder:
      arch: fc_image
      l_hidden: [1024, 1024, 1024, ]
      activation: ['elu', 'elu', 'elu', ]
      out_activation: 'linear'
  decoder:
      arch: fc_image
      l_hidden: [1024, 1024, 1024, ]
      activation: ['elu', 'elu', 'elu', ]
      out_activation: 'linear'
  x_dim: 784
  z_dim: 1
optimizer:
  lr: 0.0001
training:
  num_epochs: 2001
