exp_name: NRAEL_toy_denoising
data:
  training:
    split: training
    dataset: synthetic
    type: sincurve
    num_data: 50
    noise_level: 0.3
    batch_size: 32
    graph: 
      include_center: False
      replace: True
      num_nn: 10
      bs_nn: 2
  test:
    split: test
    dataset: synthetic
    type: sincurve
    num_data: 1000
    noise_level: 0.0
    batch_size: 32
model:
  arch: nrael
  encoder:
      arch: fc_vec
      l_hidden: [512, 512, 512, ]
      activation: ['elu', 'elu', 'elu', ]
      out_activation: 'linear'
  decoder:
      arch: fc_vec
      l_hidden: [512, 512, 512, ]
      activation: ['elu', 'elu', 'elu', ]
      out_activation: 'linear'
  x_dim: 2
  z_dim: 1
  kernel: 
    type: 'binary'
    lambda: 0.01 
optimizer:
  lr: 0.001
training:
  num_epochs: 2001
